### ISSUE TITLE
Qgis - crash Wtyczka APP2

### ISSUE THREAD

**Issue by szooon1** [CyfryzacjaAPP/wtyczka_qgis_app_2#11]
Cześć,

Przy włączaniu wtyczki w menu qgis'a następuje crash z następującym komunikatem. 

Jest problem, żeby włączyć qgisa z poziomu pliku qgs, najpierw trzeba odpalić czystego qgisa, wyłączyć wtyczkę i wtedy można działać. 

Coś jest z kodem czy wina użytkownika? 

![image (3)](https://github.com/user-attachments/assets/426d83c3-c62d-444e-aa6f-85a26937fecc)

**Comment by MarcinLebiecki** [comment]
Proszę o informację jaka wersja wtyczki była użyta.

**Comment by szooon1** [comment]
Wersja wtyczki 1.2.1

**Comment by CyfryzacjaAPP** [comment]
Dziękujemy za zgłoszenie. Prosimy o informację, jeśli opisana sytuacja powtarza się w najnowszej wersji Wtyczki APP 2.0.5.
