### ISSUE TITLE
Wybór profilu podstawowego - brak możliwości modyfikacji listy

### ISSUE THREAD

**Issue by pankonduktortoja** [CyfryzacjaAPP/wtyczka_qgis_app_2#12]
Dzień dobry,
Używam wersji wtyczki 2.0.5 na wersji programu 3.34.4
Podczas tworzenia strefy planistycznej w formularzu da się rozwinąć listę z profilem podstawowym, ale nie da się odznaczyć żadnego elementu (wszystkie elementy są od razu odhaczone).
W przypadku wyboru profilu dodatkowego wszystkie opcje są odznaczone i jest możliwość wyboru odpowiadających profili dodatkowych.
Spojrzałem do kodu i nie ma tam żadnej logiki umożliwiającej wybór elementów z listy dla profilu podstawowego, ale nie jest to sprecyzowane w ustawie bądź rozporządzeniu, a z punktu planowania takie podejście jest nielogiczne.
Proszę o informację, czy brak możliwości edycji listy profilu podstawowego dla strefy planistycznej był zamierzony.

**Comment by CyfryzacjaAPP** [comment]
Dziękujemy za zgłoszenie. Brak możliwości odznaczenia we wtyczce terenów w profilu podstawowym jest działaniem celowym. Zgodnie z §2 ust. 2 Rozporządzenia Ministra Rozwoju i Technologii z dnia 8 grudnia 2023 r. w sprawie projektu planu ogólnego gminy, dokumentowania prac planistycznych w zakresie tego planu oraz wydawania z niego wypisów i wyrysów (Dz. U. 2023 r. poz. 2758) w każdej strefie planistycznej profil funkcjonalny **obejmuje** tereny określone w ramach profilu funkcjonalnego podstawowego oraz **może obejmować** tereny określone w ramach profilu funkcjonalnego dodatkowego. Z powyższego zapisu wynika stała wartość dla profilu podstawowego danej strefy.
