### ISSUE TITLE
Zbiór app błędy 

### ISSUE THREAD

**Issue by LukPiskur** [CyfryzacjaAPP/wtyczka_qgis_app_2#13]
Dzień dobry. 
po wygenerowaniu APP i próbie wyświetlenia pod adresem 
https://aplikacje.gov.pl/app/gov_xml_validator/
Występują  błędy jak w załączonym pliku zgodnie z raportem. 
Z analizy wychodzi że jest to błąd w godzinie. w większości przypadków dokładnie o 2 godziny. 
[Raport_POG_test_2024-09-10_11-08.txt](https://github.com/user-attachments/files/16945883/Raport_POG_test_2024-09-10_11-08.txt)
![ScreenHunter 06](https://github.com/user-attachments/assets/be3bdfbc-0c15-4629-98e8-f7dc4c026270)

**Comment by EwaKomedera** [comment]
Dzień dobry.

Pragnę zgłosić, że mam ten sam problem co przedmówca.

Po utworzeniu pliku GML dla Planu ogólnego, etap przystąpienia, po dokonaniu walidacji pliku GML otrzymuje informacje o błędzie:
Element "app:wersjaId" nie jest zgodny z elementem: "app:poczatekWersjiObiektu".

W trakcie wypełniania atrybutów dla POG, warstwy: AktPlanowaniaPrzestrzennego, godziny w komórkach: "identyfikator wersji" i "początek wersji obiektu" są takie same (jednak przesunięte o 2 godz. w stosunku do godziny jaka jest w Polsce), a następnie po zapisaniu GML'a godziny w tych dwóch komórkach różnią się dodatkowo od siebie o 2 h.
W załączeniu zrzuty ekranu z pokazaniem błędu.

Używam:
Wersja QGIS 3.34.10-Prizren
Wtyczka APP, wersja 2.0.5

Proszę o informację czy to jest błąd po mojej stronie, czy błąd Wtyczki i ew. jak można temu zaradzić.

Pozdrawiam,
Ewa Komędera

![1_Etap wypełniania danych](https://github.com/user-attachments/assets/42e760d6-3142-4435-9c82-70ad888637d4)
![2_Etap po utworzeniu GMLa](https://github.com/user-attachments/assets/0a1ecccb-2095-49fe-a137-abded99d39f0)
![3_Walidacja](https://github.com/user-attachments/assets/8de2dcec-92b0-4474-beb5-2079eff9fa9f)

**Comment by CyfryzacjaAPP** [comment]
Dziękujemy za zgłoszenie. Prosimy o informację, jeśli opisana sytuacja powtarza się w najnowszej wersji Wtyczki APP 2.0.6.
