### ISSUE TITLE
Generowanie OUZ

### ISSUE THREAD

**Issue by Edixn98** [CyfryzacjaAPP/wtyczka_qgis_app_2#15]
Przeprowadzone zostały 3 próby wygenerowania obszaru OUZ na danych dla Warszawy na wtyczce APP 2.0.5, na rożnych komputerach, wersji QGIS 3.34.8, 3.22.4 oraz 3.28.

Generowanie trwało kilka godzin, podczas którego działanie programu było zawieszone, powstała warstwa wektorowa, ale nie wygenerował się folder „Dane pomocnicze”.

Pojawiły się poniższe błędy Pythona:

![obraz](https://github.com/user-attachments/assets/3e42fda9-8d86-4187-89da-e156acbed1e8)
![obraz](https://github.com/user-attachments/assets/de2f7b80-e89b-4625-b85a-f23a93850f8d)

Proszę o informacje z czego wynikają powyższe błędy.

**Comment by CyfryzacjaAPP** [comment]
Dziękujemy za zgłoszenie. Prosimy o informację, jeśli opisana sytuacja powtarza się w najnowszej wersji Wtyczki APP 2.0.6.
