### ISSUE TITLE
oznaczenie i symbol

### ISSUE THREAD

**Issue by Uzytko** [CyfryzacjaAPP/wtyczka_qgis_app_2#18]
Wtyczka samoistnie potrafi zmienić wszystkie nazwy w oznaczeniach i symbolach, i cały rysunek robi zielony np. jako strefa otwarta SO. Dwukrotny przypadek.

**Comment by MateuszOlender** [comment]
Zdarza mi się dokładnie to samo. Wszystko nagle potrafi znikać. Brak mi już słów i cierpliwości na to.

**Comment by CyfryzacjaAPP** [comment]
Dziękujemy za zgłoszenie. Prosimy o informację, jeśli opisana sytuacja powtarza się w najnowszej wersji Wtyczki APP 2.0.6.
