### ISSUE TITLE
Niepoprawne atrybuty poczatekWersjiObiektu i wersjaID

### ISSUE THREAD

**Issue by MateuszOlender** [CyfryzacjaAPP/wtyczka_qgis_app_2#19]
Dzień dobry,

przy tworzeniu/edytowaniu stref planistycznych natrafiam na problem. 
Otóż atrybuty wersjaId oraz poczatekWersjiObiektu tworzą się różne przez co tworzony GML finalny zawiera błędy i nie działa.

Przy wypełnianiu atrybutów wszystko jest okej. Godziny się zgadzają. 

![image](https://github.com/user-attachments/assets/dd711291-86ff-4351-9c42-b37837d76393)

Natomiast po zatwierdzeniu i w tabeli atrybutów tworzy się coś takiego...

![image](https://github.com/user-attachments/assets/1c691496-85c4-4ca3-8f61-731d91da373f)

Dlaczego tworzą się różne atrybuty? 

![image](https://github.com/user-attachments/assets/0be02eae-e174-4ad7-9eab-aa31ddf1dcce)

**Comment by MateuszOlender** [comment]
Czy jest ktokolwiek w stanie pomóc?

**Comment by CyfryzacjaAPP** [comment]
Dziękujemy za zgłoszenie. Prosimy o informację, jeśli opisana sytuacja powtarza się w najnowszej wersji Wtyczki APP 2.0.6.
