### ISSUE TITLE
Plugin APP2 - błąd aplikacji QGIS przy starcie

### ISSUE THREAD

**Issue by sapas1** [CyfryzacjaAPP/wtyczka_qgis_app_2#4]
Witam

Chciałbym zgłosić problem z wtyczką APP2. Po zainstalowaniu wtyczki, po kolejnym uruchomieniu Qgis pojawia się błąd typu "Python Stack Trace, Windows fatal exception: access violation...", po czym Qgis się zamyka.

Z obserwacji wynika, że jeśli w Qgis są otwarte jakieś mapy/podkłady/rysunki i wtyczka jest zainstalowana to Qgis się wywraca. Jeśli użytkownik ma otwartego "gołego" Qgisa to daje się pracować w APP2 a po zakończeniu prac trzeba odinstalować wtyczkę.

W/w błąd pojawia się prawie zawsze (ale zdarzają się dni/okresy kiedy problem chwilowo znika)
Testowano na dwóch laptopach Dell, ze świeżą instalacją W10 Home PL 22H2 + aktualizacje, MS Office 2010, FF, podstawowy AV.

Ostatnio testowane wersje Qgis to 3.32 Lima i 3.34.4 Prizren
Używano wtyczkę w wersji 1.2.1 i 2.0.2

W załączeniu przykładowe zrzuty raportowanych błędów
[Stack trace 1.txt](https://github.com/CyfryzacjaAPP/wtyczka_qgis_app_2/files/14842050/Stack.trace.1.txt)
[Stack trace 2.txt](https://github.com/CyfryzacjaAPP/wtyczka_qgis_app_2/files/14842051/Stack.trace.2.txt)

Jeśli mam przesłać jakieś dodatkowe dane lub wykonać jakieś testy to proszę o info.
Pozdrawiam

**Comment by KasiaZagrobelna** [comment]
Dzień dobry, czy błąd dalej występuje na nowej wersji wtyczki - 2.0.3?

**Comment by sapas1** [comment]
Witam. Nie wiem, muszę przetestować z nową wersją wtyczki. Jak pisałem zgłoszenie to 2.0.2 była najnowszą wersją. Pozdrawiam.

**Comment by sapas1** [comment]
Witam. Przetestowano na wersji 2.0.3. Jest lepiej, teraz nie wiesza aplikacji przy starcie. Dziękuję za poprawkę.
Pozdrawiam
