### ISSUE TITLE
Wtyczka generuje plik gml, który nie przechodzi walidacji przez oficjalny walidator.

### ISSUE THREAD

**Issue by akiwior** [CyfryzacjaAPP/wtyczka_qgis_app_2#5]
Po wygenerowaniu pliku gml przez wtyczkę walidator ze strony internetowej zwraca błąd:
Wersja walidatora: 2.0.9
Plik o nazwie 179_gml_uchwalenie_24_04_2024.gml i idIIP = PL.ZIPPZP.2177_226301-MPZP_179_armii-krajowej_uchwalenie_20240424T000000 w dniu 24.04.2024 o godzinie 12:08 jest niezgodny ze schematem aplikacyjnym dostępnym pod adresem: https://www.gov.pl/static/zagospodarowanieprzestrzenne/schemas/app/1.0/planowaniePrzestrzenne.xsd
Adres serwisu: https://www.gov.pl/zagospodarowanieprzestrzenne
Adres usługi walidacji: https://aplikacje.gov.pl/app/gov_xml_validator

Informacja o błędzie: Brak wskazania schematu aplikacyjnego: https://www.gov.pl/static/zagospodarowanieprzestrzenne/schemas/app/1.0

**Comment by KasiaZagrobelna** [comment]
Wtyczka eksperymentalna generuje pliki zgodne ze schematem aplikacyjnym "Planowanie Przestrzenne 2.0", zaś walidator w wersji 2.0.9 operuje na schemacie aplikacyjnym "Planowanie Przestrzenne 1.0" - i stąd ten komunikat. 
W celu wygenerowania plików w poprzedniej wersji schematu — rekomendujemy w dalszym ciągu używać ostatniej stabilnej wersji Wtyczki (1.2.1).

**Comment by KasiaZagrobelna** [comment]
@akiwior By zwalidować pliki utworzone w schemacie 2.0 - testujemy obecnie nową wersję Przeglądarki danych planistycznych. Proszę o maila na cyfryzacja.app@mrit.gov.pl - to udostępnimy dane dostępowe do nowej wersji Przeglądarki.
