### ISSUE TITLE
bład walidacji pliku gml dla PO we wtyczce APP2

### ISSUE THREAD

**Issue by MagdalenaKarlikowska** [CyfryzacjaAPP/wtyczka_qgis_app_2#6]
po wygenerowaniu danych przestrzennych do pliku gml, nie przechodzi on walidacji na stronie https://www.gov.pl/web/gov/sprawdz-poprawnosc-danych-przestrzennych-oraz-metadanych#l

gml wykonany we wtyczce wersja 2.0.3

treść raportu:

Wersja walidatora: 2.0.9
Plik o nazwie TRZ.POG1_gml.przystapienie.gml i idIIP = PL.ZIPPZP.9663_022003-POG_a220f96a-47a2-4ec6-aae0-bad8481ab500_20240529T070737 w dniu 29.05.2024 o godzinie 09:24 jest niezgodny ze schematem aplikacyjnym dostępnym pod adresem: https://www.gov.pl/static/zagospodarowanieprzestrzenne/schemas/app/1.0/planowaniePrzestrzenne.xsd
Adres serwisu: https://www.gov.pl/zagospodarowanieprzestrzenne
Adres usługi walidacji: https://aplikacje.gov.pl/app/gov_xml_validator

Informacja o błędzie: Brak wskazania schematu aplikacyjnego: https://www.gov.pl/static/zagospodarowanieprzestrzenne/schemas/app/1.0

Numer linii: 15
Informacja o błędzie: plan ogólny gminy nie jest poprawną wartością dla atrybutu „typPlanu”. Dziedzinę wartości atrybutu „typPlanu” stanowi lista kodowa Typ aktu planowania przestrzennego.

Numer linii: 12
Informacja o błędzie: Data wprowadzona w app:AktPlanowaniaPrzestrzennego jako wartość atrybutu app:poczatekWersjiObiektu ma nieprawidłowy format.

**Comment by KasiaZagrobelna** [comment]
Szanowna Pani — odpowiedź na Pani uwagę jest taka sama jak w zgłoszeniu #5 (https://github.com/CyfryzacjaAPP/wtyczka_qgis_app_2/issues/5). Przeklejam ją poniżej: 

Wtyczka eksperymentalna generuje pliki zgodne ze schematem aplikacyjnym "Planowanie Przestrzenne 2.0", zaś walidator w wersji 2.0.9 operuje na schemacie aplikacyjnym "Planowanie Przestrzenne 1.0" - i stąd ten komunikat.
W celu wygenerowania plików w poprzedniej wersji schematu — rekomendujemy w dalszym ciągu używać ostatniej stabilnej wersji Wtyczki (1.2.1).
By zwalidować pliki utworzone w schemacie 2.0 - testujemy obecnie nową wersję Przeglądarki danych planistycznych. Proszę o maila na [cyfryzacja.app@mrit.gov.pl](mailto:cyfryzacja.app@mrit.gov.pl) - to udostępnimy dane dostępowe do nowej wersji Przeglądarki.
