### ISSUE TITLE
Błędy w atrybutach - kolumna "obowiazujeDo"

### ISSUE THREAD

**Issue by Edixn98** [CyfryzacjaAPP/wtyczka_qgis_app_2#9]
Dzień dobry, według formularza uzupełniania atrybutów na warstwie strefa planistyczna data "ObowiązujeDo" nie jest obowiązkowa. Ale gdy zostawiam ją pustą, podczas próby zapisania warstwy do gml tworzy mi się warstwa z błędami w atrybutach i pojawia się błąd dla wszystkich stref: 

![obraz](https://github.com/CyfryzacjaAPP/wtyczka_qgis_app_2/assets/173901688/b18bd039-4cad-446f-9259-f713b05355b8)

Dlaczego data ta jest obowiązkowa? Status wybrałam "w opracowaniu" jeżeli ma to jakieś znaczenie.

**Comment by Edixn98** [comment]
podane przeze mnie błędy nadal występują w wersji wtyczki 2.0.4

**Comment by CyfryzacjaAPP** [comment]
Dziękujemy za zgłoszenie. Prosimy o informację, jeśli opisana sytuacja powtarza się w najnowszej wersji Wtyczki APP 2.0.5.
